// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iseuglpyvgvqygvsojgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZXVnbHB5dmd2cXlndnNvamdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NjAzOTYsImV4cCI6MjA2MDMzNjM5Nn0.PeugFuURb3nIYYvVcv-DQfs49VvG7vJG8EFymfnhwAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);